site_name: Read Notes
site_url: https://doc.jinvic.top/read-notes
repo_url: https://github.com/Jinvic/read-notes
repo_name: Jinvic/read-notes
site_description: read notes of some books.
site_author: Jinvic

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.expand
    - navigation.path
    # - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - 首页: index.md
  - tech:
    - go:
      - Go程序设计语言: 《Go程序设计语言》阅读笔记/index.md
      - Go语言高级编程:  《Go语言高级编程》阅读笔记/index.md
    - cpp:
      - CppPrimerPlus:  【学习笔记】C++-Primer-Plus（第6版）【基础篇】/index.md
    - sql:
      - SQL必知必会: 《SQL必知必会》阅读笔记/index.md



plugins:
  - search:
      lang:
        - zh
        - en
        - jp

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true  # 可选：启用更紧凑样式

